<?php
/**
 * 
 *
 * @author Joseph Maxwell
 * @copyright Swift Otter Studios, 3/14/13
 * @package default
 **/

class SwiftOtter_Report_Block_Adminhtml_Report_ProductSaleRegion_Filter extends SwiftOtter_Base_Block_Admin_Form_Filter
{
    /**
     * @param Varien_Data_Form_Element_Fieldset $fieldset
     * @return $this
     */
    protected function _addAdditionalFields($fieldset, $filter)
    {
        $fieldset->addField('show_regions', 'select', array(
            'label' => $this->__('Show Regions (for filtering)'),
            'name'  => 'show_regions',
            'id'    => 'show_regions',
            'class' => 'form-custom',
            'type' => 'options',
            'options' => array('0' => 'No', '1' => 'Yes')
        ));

        return parent::_addAdditionalFields($fieldset, $filter);
    }

    protected function _formatInputParams($params)
    {

        return parent::_formatInputParams($params); // TODO: Change the autogenerated stub
    }


}